[[hicolor_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "48b0414b06162da51802e1f389ac591eae67adbd"
os = "macos"

    [[hicolor_icon_theme.download]]
    sha256 = "899a512785dce3c8f5b0cbcf13a958bdb830b3ba849b396027095c51439cff0f"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.x86_64-apple-darwin14.tar.gz"
[[hicolor_icon_theme]]
arch = "i686"
git-tree-sha1 = "264381d6baefb65d8ea3cda6008754126359bb6e"
libc = "glibc"
os = "linux"

    [[hicolor_icon_theme.download]]
    sha256 = "070f7c240615ba084391196a90ab4893f4653517200a12ae16d84d9cf5c23717"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.i686-linux-gnu.tar.gz"
[[hicolor_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "1d903f4553bd3e877d69f522aba1c57fd4f87289"
os = "freebsd"

    [[hicolor_icon_theme.download]]
    sha256 = "5913a13a0cbcb8f2f606139248e20e6ef21df958c3c44c885f0772ce734d5a2b"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.x86_64-unknown-freebsd11.1.tar.gz"
[[hicolor_icon_theme]]
arch = "powerpc64le"
git-tree-sha1 = "74a616e594dcbbb6294d1da4761faefd9733e6b0"
libc = "glibc"
os = "linux"

    [[hicolor_icon_theme.download]]
    sha256 = "08f5daab6bca1f30a957459c56a29073771522259b67d551a726b11f55fce280"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.powerpc64le-linux-gnu.tar.gz"
[[hicolor_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "dce712ca4bf9a7bbea0635183fcdb602825e8275"
libc = "musl"
os = "linux"

    [[hicolor_icon_theme.download]]
    sha256 = "fc0b1887a92096888d521a8bcf47334275ed98bd40edcfe3d9b971dbf26ba9bb"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.x86_64-linux-musl.tar.gz"
[[hicolor_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "3e4e9a264ff818fdc52626ae4b3e478bc09d7b04"
libc = "glibc"
os = "linux"

    [[hicolor_icon_theme.download]]
    sha256 = "9571ca8f24685efd78eda226360ff6b63e5fb96e64728922649ba3551de0d82e"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.x86_64-linux-gnu.tar.gz"
[[hicolor_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "e5ebfe8dc1637f732d5054c273baad18326459f4"
os = "windows"

    [[hicolor_icon_theme.download]]
    sha256 = "8010d21dd33f5f7d87bef4b77593acd6a2ce88580863d1daf1cf69fc89dd5084"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.x86_64-w64-mingw32.tar.gz"
[[hicolor_icon_theme]]
arch = "aarch64"
git-tree-sha1 = "db85e0c3e2c59f5889f2e0f92faa965f1af8f10d"
libc = "musl"
os = "linux"

    [[hicolor_icon_theme.download]]
    sha256 = "fc627ea23d9413e0adedfc46e18c487b8fb539b40590c78db87c7bd10ef194a6"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.aarch64-linux-musl.tar.gz"
[[hicolor_icon_theme]]
arch = "armv7l"
git-tree-sha1 = "64b5449413ba8008622479721e4881a61111716c"
libc = "glibc"
os = "linux"

    [[hicolor_icon_theme.download]]
    sha256 = "02fe4378a243b993e37197758037889fe894bd1f0f552f4dbc93eda84f9da9ea"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.arm-linux-gnueabihf.tar.gz"
[[hicolor_icon_theme]]
arch = "i686"
git-tree-sha1 = "658de5dc396e498413566fb3f11b2173523da7ec"
libc = "musl"
os = "linux"

    [[hicolor_icon_theme.download]]
    sha256 = "2193b4deaaf6c0b45d15e4eaf179032be10518e691ac8e0fdc7ddb942010c884"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.i686-linux-musl.tar.gz"
[[hicolor_icon_theme]]
arch = "armv7l"
git-tree-sha1 = "46988c7a6f4a90663d0c2ac341ff55d51e940cf8"
libc = "musl"
os = "linux"

    [[hicolor_icon_theme.download]]
    sha256 = "947764fa2d57bd39a61e429e576c8c88a7321508314295383af1534d666edf9c"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.arm-linux-musleabihf.tar.gz"
[[hicolor_icon_theme]]
arch = "aarch64"
git-tree-sha1 = "cfe7d666e6f4f92cdac35ea96e5b80cf5b7b5f2c"
libc = "glibc"
os = "linux"

    [[hicolor_icon_theme.download]]
    sha256 = "f487aacada602606f20d644b6e8d0abdb8403502d7a09ab8c3122efee944f154"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.aarch64-linux-gnu.tar.gz"
[[hicolor_icon_theme]]
arch = "i686"
git-tree-sha1 = "ff8697644fcb07f5d47eaca9c75e164247e5ce88"
os = "windows"

    [[hicolor_icon_theme.download]]
    sha256 = "794a10c31ad2da14c6467dd0686b905dd98d9597a74ab5d396e45459b325bb79"
    url = "https://github.com/JuliaBinaryWrappers/hicolor_icon_theme_jll.jl/releases/download/hicolor_icon_theme-v0.17.0+1/hicolor_icon_theme.v0.17.0.i686-w64-mingw32.tar.gz"
